// -------------------- Imports --------------------
const Images = {
    logo:"/Images/logo.png",
    homeTitle:"/Images/home-title.jpg",
    titleLoo:"/Images/title-logo.jpg",
    servicesBg:"/Images/services-bg.jpg",
    device1:"/Images/device1.png",
    device2:"/Images/device2.png",
    device4:"/Images/device4.png",
    automation:"/Images/automation.jpg",
    education:"/Images/education.jpg",
    research:"/Images/research.jpg",
    inovationBg:"/Images/inovation-bg.jpg",
    latest1:"/Images/17-single.png",
    latest2:"/Images/process-view.png",
    latest3:"/Images/flx-cs100.png",
    service1:"/Images/1ee.png",
    service2:"/Images/2as.png",
    service3:"/Images/3ms.png",
    service4:"/Images/4ias.png",
    service5:"/Images/5ici.png",
    service6:"/Images/6rie.png",
    service7:"/Images/7sit.png",
    service8:"/Images/8ass.png",
    simulationHeader:"/Images/simulation-header.jpg",
    laptop:"/Images/lap.png",
    userReviews:"/Images/userReviews.jpg",
    found1:"/Images/fund1.jpg",
    found2:"/Images/fund2.jpg",
    found3:"/Images/fund3.jpg",
    found4:"/Images/fund4.jpg",
    protectYou:"/Images/protectInvestment.jpg",
    p1:"/Images/p1.png",
    p2:"/Images/p2.png",
    p3:"/Images/p3.png",
    p4:"/Images/p4.png",
    footer:"/Images/footer.png",
}

// -------------------- Exports --------------------
export { Images };
